import type { Metadata } from 'next';
import './globals.css';
import { GeistSans } from 'geist/font/sans';
import { DARK_TOKENS, LIGHT_TOKENS } from '@/lib/constants';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = 'dark';
  return (
    <html
      lang="en"
      style={
        theme === 'dark'
          ? (DARK_TOKENS as React.CSSProperties)
          : (LIGHT_TOKENS as React.CSSProperties)
      }
    >
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
